version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongo_pix_security
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_DATABASE: pix_security